#!/usr/bin/env bash

set -u

readonly X_PHYSICAL_END=17
readonly Y_PHYSICAL_END=11

x_logical_current=0
y_logical_current=0
x_physical_current=1
y_physical_current=1

clear_screen() {
  echo -n -e '\033[H\033[2J'
}

move_cursor() {
  x_physical_current=$1
  y_physical_current=$2
  echo -n -e "\033[${2};${1}H"
}

move_cursor_down() {
  if (( y_physical_current == Y_PHYSICAL_END )); then
    return
  elif (( y_physical_current == 3 )) || (( y_physical_current == 7 )); then
    # to go over split-line
    y=$((y_physical_current + 2))
  else
    y=$((y_physical_current + 1))
  fi
  move_cursor $x_physical_current $y
}

go_down() {
  if (( y_logical_current < 8 )); then
    y_logical_current=$((y_logical_current + 1))
  fi
  move_cursor_down
}

move_cursor_up() {
  if (( y_physical_current == 1 )); then
    return
  elif (( y_physical_current == 5 )) || (( y_physical_current == 9 )); then
    # to go over split-line
    y=$((y_physical_current - 2))
  else
    y=$((y_physical_current - 1))
  fi
  move_cursor $x_physical_current $y
}

go_up() {
  if (( y_logical_current > 0 )); then
    y_logical_current=$((y_logical_current - 1))
  fi
  move_cursor_up
}

move_cursor_left() {
  (( x_physical_current == 1 )) && return
  move_cursor $((x_physical_current - 2)) $y_physical_current
}

go_left() {
  if (( x_logical_current > 0 )); then
    x_logical_current=$((x_logical_current - 1))
  fi
  move_cursor_left
}

move_cursor_right() {
  (( x_physical_current == X_PHYSICAL_END )) && return
  move_cursor $((x_physical_current + 2)) $y_physical_current
}

go_right() {
  if (( x_logical_current < 8 )); then
    x_logical_current=$((x_logical_current + 1))
  fi
  move_cursor_right
}

set_value() {
  x=${x_logical_current}
  y=${y_logical_current}
  eval given=\$givens_"${y}"_"${x}"
  if [[ "$given" == yes ]]; then
    return
  fi

  val="${1}"
  eval values_"${y}"_"${x}"=${val}

  # Prevent cursor move by entering multiple numbers at the same time
  echo -e -n "${val}\033[${y_physical_current};${x_physical_current}H"
}

gen_problem() {
  sample_problem=".,.,.,6,3,.,.,.,., .,8,.,.,.,2,3,1,., .,9,.,8,.,.,.,.,., .,7,.,.,.,.,6,.,9, 9,.,.,.,.,.,.,.,8, 1,.,5,.,.,.,.,4,., .,.,.,.,.,4,.,2,., .,4,6,5,.,.,.,3,., .,.,.,.,9,1,.,.,.,"
  echo "$sample_problem"
}

init_data() {
  IFS_BAK=$IFS
  y=0
  problem=$(gen_problem)
  for row in $problem; do
    IFS=,
    x=0
    for c in $row; do
      eval values_"${y}"_"${x}"=$c
      if [[ "$c" != '.' ]]; then
        eval givens_"${y}"_"${x}"=yes
      else
        eval givens_"${y}"_"${x}"=no
      fi
      x=$((x + 1))
    done
    y=$((y + 1))
    IFS=$IFS_BAK
  done
}

clear_number() {
  echo -n .
  move_cursor $x_physical_current $y_physical_current
}

print_grid() {
  for y in {0..8}; do
    for x in {0..8}; do
      eval val=\$values_"${y}"_"${x}"
      if [[ "$val" != '.' ]]; then
        # Print underline for given numbers
        echo -ne "\033[4m${val}\033[0m"
      else
        echo -n '.'
      fi
      if (( x == 2 || x == 5 )); then
        echo -n '|'
      else
        echo -n ' '
      fi
    done
    echo
    if (( y == 2 || y == 5 )); then
      echo '-----|-----|-----'
    fi
  done
}

init() {
  init_data
  clear_screen
  print_grid
  move_cursor 1 1
}

quit() {
  clear_screen
  exit 0
}

init

while :; do
  read -s -n 1 key
  case "$key" in
    j) go_down ;;
    k) go_up ;;
    h) go_left ;;
    l) go_right ;;
    [1-9.]) set_value "$key" ;;
    q) quit ;;
  esac
done
